class PaymentProcessor:
    def process(self): pass

class LoggedValidatedPayment(PaymentProcessor): ...
class ValidatedEncryptedPayment(PaymentProcessor): ...
class LoggedEncryptedPayment(PaymentProcessor): ...
# ... explosion continues